import streamlit as st
import plost
import pandas as pd
import numpy as np
from datetime import datetime
from functions.setup_page import page_creation

## Apply standard page settings.
st.set_page_config(
    layout="wide",
    initial_sidebar_state="expanded",
)

st.title('Subscriptions Report')

## Define data and filters. The resulting data variable includes the data with all filters applied.
data = page_creation()

st.divider()

st.dataframe(data.head(10)) ## This is here just as an example. This can be deleted during development and before release.

st.divider()

# Everything below this point will be generated by the assigned analyst. 
# The framework has been set, but no visualization or data processing has been applied.
# Please perform any data processing in this file and not within the filter files. We can discuss upon completion if it makes sense to add any code to the filters file.

## KPI Metrics which need to be updated.
with st.container():
    col1, col2, col3, col4, col5 = st.columns(5)

    with col1:
        st.metric(label="**Total Revenue From Subscriptions**", value="TBD")

    with col2:
        st.metric(label="**Active Subscriptions**", value="TBD")

    with col3:
        st.metric(label="**New Subscriptions**", value="TBD")

    with col4:
        st.metric(label="**Average Subscription Length (weeks)**", value="TBD")

    with col5:
        st.metric(label="**MRR**", value="TBD")

# Time series charts need to be built out
with st.container():
    row1_col1, row1_col2 = st.columns(2)
    row2_col1, row2_col2 = st.columns(2)

    with row1_col1:
        st.markdown("**Number of New Subscriptions**")

    with row1_col2:
        st.markdown("**Number of New Subscriptions by Plan**")

    with row2_col1:
        st.markdown("**Subscription Revenue by Product Type**")

    with row2_col2:
        st.markdown("**Subscription Revenue vs. Single Order Revenue**")